name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Copy APK to artifacts
        run: cp app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/artifacts
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ${{ github.workspace }}/artifacts/app-debug.apk
